### ISSUE TITLE
forbidden error

### ISSUE THREAD

**Issue by yuu2lee4** [tunnckoCore/koa-better-serve#3]
`ForbiddenError: Forbidden
    at resolvePath (/Users/yuri/work/library_be/node_modules/resolve-path/index.js:82:11)
    at /Users/yuri/work/library_be/node_modules/koa-send/index.js:69:12
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/yuri/work/library_be/node_modules/co/index.js:65:19)
    at /Users/yuri/work/library_be/node_modules/co/index.js:54:5
    at co (/Users/yuri/work/library_be/node_modules/co/index.js:50:10)
    at send (/Users/yuri/work/library_be/node_modules/koa-send/index.js:36:10)
    at /Users/yuri/work/library_be/node_modules/koa-better-serve/index.js:63:16
    at process._tickCallback (internal/process/next_tick.js:109:7`

**Comment by hugski** [comment]
same error stack , my code is 
`app.use(serve('./temp', '/content'));`

**Comment by tunnckoCore** [comment]
Looks like your path where it tries to read don't have read permissions.

If fixing the permissions using `chmod` or something like it, then forward the issue directly to the `koa-send` package, because we do nothing here - this is just a wrapper for it, you can see that from the stack trace.

Try `chmod -R 755 ./temp` or at least `655`.

Hope this help and sorry for the delay, folks!
